apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    editable: false
    jsonData:
      defaultDatabase: equity_raw
      host: ${CLICKHOUSE_HOST}
      port: ${CLICKHOUSE_PORT}
      protocol: http
      readonly: true
      username: grafana_readonly
    secureJsonData:
      password:
